environment: dev
seed: india-seed
isMasterSeed: false

kkpBasePath: "."

repoURL: https://github.com/dharapvj/temp-argocd-test.git
valuesPathPrefix: "." # This is prefix wrt environment folder e.g. /dev/

# KKP Core
nginx: true
certManager: true
oauth: false # not configuring seed-local-dex yet. Its TODO:
seedSettings: true
seedExtras: true

#monitoring
prometheus: true
alertManager: true
grafana: true
kubeStateMetrics: true
nodeExporter: true
blackboxExporter: true
# FIXME: Get thanos deployment to work as we expect it
thanos: false    # This gets installed from upstream (bitnami / banzai / stevehipwell) directly
iapSeedMla: true

#logging
promtail: true
loki: true

#backup
velero: true

# storage
minio: true

#user cluster mla
userMla:
  enable: true # master switch to control whether you want to deploy user-cluster MLA or not
  minio: true
  minioLifecycleMgr: true
  grafana: true
  consul: true
  cortex: true
  lokiDistributed: true
  alertmanagerProxy: true
  iapMla: true
  secrets: true