apiVersion: v1
data:
# TODO: I think we will need to pre-create the bucket and user in minio for this to work!
# via minio configuration? below commands do the trick manually for now
# mc admin user add minio Pbea0rmZF1z5yPRt TTkGamIu9SibifSR
# mc admin policy attach minio readwrite --user Pbea0rmZF1z5yPRt
  accessKey: UGJlYTBybVpGMXo1eVBSdA==
  bucket: bWV0ZXJpbmctc2VsZi1zZWVk
  endpoint: aHR0cDovL21pbmlvLm1pbmlvLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA=
  region: ZXUtY2VudHJhbC0x
  secretKey: VFRrR2FtSXU5U2liaWZTUg==
kind: Secret
metadata:
  name: metering-s3
  namespace: kubermatic 
type: Opaque
