apiVersion: v1
data:
  accessKey: UGJlYTBybVpGMXo1eVBSdA==
  bucket: bWV0ZXJpbmctc2VsZi1zZWVk
  endpoint: aHR0cHM6Ly9taW5pby5taW5pby5zdmMuY2x1c3Rlci5sb2NhbA==
  region: ZXUtY2VudHJhbC0x
  secretKey: VFRrR2FtSXU5U2liaWZTUg==
kind: Secret
metadata:
  name: metering-s3
  namespace: kubermatic 
type: Opaque
