# FIXME: this needs to get installed along with / AFTER cert-manager ArgoCD chart because it needs ClusterIssuer CRD
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: vijay@kubermatic.com
    privateKeySecretRef:
      name: letsencrypt-prod-acme-account-key
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx