apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

versions:
  kubernetes: 1.30.2

cloudProvider:
  aws: {}
  external: true

containerRuntime:
  containerd: {}

clusterNetwork:
  cni:
    external: {}
  
addons:
  enable: true
  addons:
    - name: default-storage-class
    - name: cluster-autoscaler
    - name: calico-vxlan
