apiVersion: v1
kind: Secret
metadata:
  name: seed-dev-self-kubeconfig
  namespace: kubermatic
type: Opaque
data:
  # You can use `base64 -w0 ./seed-ready-kube-config` to encode the
  # kubeconfig properly for inserting into this Secret.
  kubeconfig: <your base64 encoded kubeconfig>
