apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    # TODO: This label is very weird.. I would say. We should customize this label to alert-rules or something in kps values.yaml
    release: kube-prometheus-stack
  name: cert-manager-rules
  namespace: monitoring1
spec:
  groups:
  - name: cert-manager
    rules:
      - alert: CertManagerCertExpiresSoon
        annotations:
          message: The certificate {{ $labels.name }} expires in less than 3 days.
          runbook_url: https://docs.kubermatic.com/kubermatic/main/cheat-sheets/alerting-runbook/#alert-certmanagercertexpiressoon
        expr: certmanager_certificate_expiration_timestamp_seconds - time() < 3*24*3600
        labels:
          severity: warning
          resource: "{{ $labels.name }}"
          service: cert-manager
      - alert: CertManagerCertExpiresVerySoon
        annotations:
          message: The certificate {{ $labels.name }} expires in less than 24 hours.
          runbook_url: https://docs.kubermatic.com/kubermatic/main/cheat-sheets/alerting-runbook/#alert-certmanagercertexpiresverysoon
        expr: certmanager_certificate_expiration_timestamp_seconds - time() < 24*3600
        labels:
          severity: critical
          resource: "{{ $labels.name }}"
          service: cert-manager
