apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca-bundle
  namespace: kubermatic
data:
  # The key must be "ca-bundle.pem".
  ca-bundle.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
    QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
    b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
    CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
    nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
    43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
    T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
    gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
    BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
    TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
    DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
    hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
    06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
    PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
    YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
    CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
    -----END CERTIFICATE-----
---

apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-staging-ca-cert
  namespace: iap
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZUVENDQXpXZ0F3SUJBZ0lSQU9PdURpVmdRRnlBVGVnUE94Zk9hNUl3RFFZSktvWklodmNOQVFFTEJRQXcKWmpFTE1Ba0dBMVVFQmhNQ1ZWTXhNekF4QmdOVkJBb1RLaWhUVkVGSFNVNUhLU0JKYm5SbGNtNWxkQ0JUWldOMQpjbWwwZVNCU1pYTmxZWEpqYUNCSGNtOTFjREVpTUNBR0ExVUVBeE1aS0ZOVVFVZEpUa2NwSUZCeVpYUmxibVFnClVHVmhjaUJZTVRBZUZ3MHlOREF6TVRNd01EQXdNREJhRncweU56QXpNVEl5TXpVNU5UbGFNRm94Q3pBSkJnTlYKQkFZVEFsVlRNU0F3SGdZRFZRUUtFeGNvVTFSQlIwbE9SeWtnVEdWMEozTWdSVzVqY25sd2RERXBNQ2NHQTFVRQpBeE1nS0ZOVVFVZEpUa2NwSUZkaGJtNWhZbVVnVjJGMFpYSmpjbVZ6Y3lCU01URXdnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ1ZZSHdlMmd4TXY5SmgvZDFCZ29jVzNhbTVFL2lCT3JMa3lFTmcKUnFMbVZsNnZOUlhnb0twUGp0UDQwTXYxN1oyTGxZaFJzbmVhSzlnZFNObU5UeEpsWTh2aXFzOWRrNFh3S0p4RApQZmwvdkpCVzRNL25KekZ3UzMwcXU3VkY4alNmeUY4MlE3S2tMbDVOeEozOVk1eXZRRnpIakwzWUNPOGNvTUc1CnY3MkREZ1d6Yys5d2sybmNvWGlCMy8zbVZnNFJ0RDF3MXhQcGRqdFNoNWtlQjdqcWduRDIvSTc1T0xCemFteTYKTkw5bmd1YUVjOGNYOENkbnBvQ0NRSTgvRno5cWhQdEpqUCtPL1JIQ3VnV1ZrU3B0dUNScmE4dGNuSlRHSFJpTgpyL0d5WXNIWlo0alo3NmhiSmp4YXB3ZjI0RThSQVZ6dU1Sc3cvblM2L2hVSjhscVBBZ01CQUFHamdnRUFNSUg5Ck1BNEdBMVVkRHdFQi93UUVBd0lCaGpBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFnWUlLd1lCQlFVSEF3RXcKRWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQURBZEJnTlZIUTRFRmdRVUU4dlg5cTZkL0dsQ1pOWmNmQ1BNaGZsSAp4N1l3SHdZRFZSMGpCQmd3Rm9BVXRmTmw4djZ3Q3BJZit6eDk4MFNnckdNbHd4UXdOZ1lJS3dZQkJRVUhBUUVFCktqQW9NQ1lHQ0NzR0FRVUZCekFDaGhwb2RIUndPaTh2YzNSbkxYZ3hMbWt1YkdWdVkzSXViM0puTHpBVEJnTlYKSFNBRUREQUtNQWdHQm1lQkRBRUNBVEFyQmdOVkhSOEVKREFpTUNDZ0hxQWNoaHBvZEhSd09pOHZjM1JuTFhneApMbU11YkdWdVkzSXViM0puTHpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWVEOXB0NXNXdFhFUXlGOTRSTXpvCmxGK3VpcCtPRFlhTnhQRUpHLzkzeHR4UGM2UUMwYnNDOVFJZ3Y2ZEJrK3MxTFVmNXVsSWxKWlExVWxrTGdUSDQKSHpIaTM3TzRpdmNiU0hwSUxjZ0QwaEtuZnR2MEU4bzlTTkFhSWNPN0RLTm1iZVdRNmNQbGZPbFJ0cGNJWFlvYwo5NXdZOUFpcE4wL2tlbjVLeER4ZHhUU0t1V1M3QWUrWldoN2htTGRmRGM1Qzg1bzJvbUx2TS82T3ZtcDB4VVNQClUveEZSMWZrMGtSbU05NzVzbWVoRU9YU0hPSjI0ekZhWTZCbk1VV2E2N3lMYXdieFVqMEFxekdtb2hkcXo3THUKRGh0S2Q5b1hKZ1J6YWNGenVNU1FsdU4waXZ3S0l6aXJwTFIvQUpvejRuSFhJYURRUnlmYUEzanIxVllwSytiQQpwb0lYQWpneFIvdkVGdGJFSHc3Zk5PM0ZLUkNkZHZ5SjB2aCtPS0lyWTBucmJHVW95UmxQbEtGLzlYclEzVUpvClpjNzA4bUJCanpxaWpYZFVRMFRCMS9pckFBUTdPLzZpK1RoUXhFbHQ3N2dZV3p2Mi84c1NvYWd6cVJLWE9xTEoKY2tOSlFJQTM5dDRITUlGZ3F4RExSdVJOdG9vRlVlb092b2NEV1RRcjgwYlVwNjM1N2NCdEFsN3lwY096clBLNgptNWN1dXlaZlE3emRoNXVmY2ZNZEZiZ2p3ZmVOOGQ0NDJFekJuTHhvTUE5VDJJZ2ZuN0tPaEZsM3puWitXSmhTCmgrb3lCUzhQcktVS0IyWG85cG5YbWE2MTIzeHlGUERhcG51SzNpaU5wR0pmSTBzVUxDcWpFb2RZRythR3lmQ3oKWkZMV2Z0YlU2ODNZeFpDT2RkZ1l4SEk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
