apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubermatic-fast
parameters:
  iopsPerGB: "25"
  type: io1
  allowAutoIOPSPerGBIncrease: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer