apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

versions:
  kubernetes: 1.30.2

cloudProvider:
  aws: {}
  external: true

containerRuntime:
  containerd: {}

addons:
  enable: true
  addons:
    - name: cluster-autoscaler
    # DEMO ONLY resource allocation. Not PROD GRADE!
    - name: cni-canal
      params:
        RequestsCPU: "60m"