apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

versions:
  kubernetes: 1.30.2

cloudProvider:
  aws: {}
  external: true

containerRuntime:
  containerd: {}

addons:
  enable: true
  addons:
    - name: cluster-autoscaler
#    - name: nodelocaldns # while nodelocaldns is highl useful, it is not great for demo since it delays external-dns created dns name resolution due to caching. So commented it out
